version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: pickleball-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pickleball_booking
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
